services:
  postgres:
    image: postgres:16
    network_mode: host
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - br_todo_pg:/var/lib/postgresql/data

volumes:
  br_todo_pg:
